package com.csye6225.fall2019.courseservice.datamodel;

//import java.util.Date;
//import javax.xml.bind.annotation.XmlRootElement;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

public class Professor {

	private Long professorId;
	private String firstName;
	private String lastName;
	private String department;
	private String joiningDate;

	public Professor() {}
	
	public Professor(Long professorId) {
		super();
		this.professorId = professorId;
	}

	public Professor(Long professorId, String firstName, 
			String lastName, String department, String string) {

		this.professorId = professorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
		this.joiningDate = string;
	}
	
	public Long getProfessorId() {
		return professorId;
	}
	public void setProfessorId(Long professorId) {
		this.professorId = professorId;
	}
	
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}


	public String getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	
	@Override
	public String toString() { 
		return "ProfId=" + getProfessorId() + ", firstName=" + getFirstName()
				+ ", department=" + getDepartment() + ", joiningDate=" + getJoiningDate().toString();
	}



}